### 查看应用全局配置
GET http://localhost:8080/admin-config/1/app
Content-Type: application/json
Authorization: basic YWRtaW46YWRtaW4=

###
### 查看应用目录配置
GET http://localhost:8080/admin-config/1/path
Content-Type: application/json
Authorization: basic YWRtaW46YWRtaW4=

###
### 查看应用 URL 配置
GET http://localhost:8080/admin-config/1/url
Content-Type: application/json
Authorization: basic YWRtaW46YWRtaW4=

###
### 模拟 403
GET http://localhost:8080/admin-config/1/url
Content-Type: application/json
Authorization: basic dXNlcjoxMTExMTE=

###