### 单文件上传
POST http://localhost:8080/1/file/upload
Authorization: basic YWRtaW46YWRtaW4=
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="element-name.txt"
Content-Type: text/plain

Element Name
--WebAppBoundary--

### 多文件上传
POST http://localhost:8080/1/file/uploads
Authorization: basic YWRtaW46YWRtaW4=
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="element-name.txt"
Content-Type: text/plain

Element Name
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="index.html"
Content-Type: text/html

< index.html

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="logback.xml"
Content-Type: application/xml

< ../logback.xml

--WebAppBoundary--

###