### 登录： JSON 模式
POST http://localhost:8080/login
Content-Type: application/json

{
  "json": {
    "username": "admin",
    "password": "admin"
  }
}

### 登录：表单模式
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=admin

### 请求：Basic 模式，无 session
GET http://localhost:8080/user/1/current
Content-Type: application/json
Authorization: basic YWRtaW46YWRtaW4=

### 修改当前登录用户昵称
PATCH http://localhost:8080/user/1/nickname
Content-Type: application/json
Authorization: basic YWRtaW46YWRtaW4=

{
  "json": {
    "nickname": "*.谢"
  }
}

### 退出
POST http://localhost:8080/logout

###