### 分页查看角色
GET http://{{host}}:{{port}}/1/role/page/1/10
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/1/role/options
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

###