app: # 生产环境 todo 编辑时注意，请同时变更其他环境对应的参数
  env: prod # 当前环境：[dev:本地|beta:测试|prod:生产]
  admin-user-id: 1 # 管理员用户ID
  admin-user: admin # 管理员账户登录账户
  ip: 127.0.0.1 # 当前主机 IP 地址；可使用 frp 服务器IP
  domain: http://localhost:8080 # 应用路径，域名；可使用 frp 服务器域名
  markdown: http://localhost:8080/md/ # markdown 文档地址
  path-root: D:/nginx/html/files # 应用文件根目录
  debug: false # 调试模式开关：true开启调试模式，false关闭调试模式
  junit: false # 单元测试开关：true开启单元测试模式，false关闭单元测试模式

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_main_db?characterEncoding=UTF-8&characterSetResults=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 111111
  #    schema: classpath:schema.sql
  #    data: classpath:database-init.sql
  data:
    mongodb:
      host: localhost
      port: 27017
      database: demo_main_db
      #uri: mongodb://name:pass@localhost/demo_main_db
