app: # 生产环境 todo 编辑时注意，请同时变更其他环境对应的参数
  env: prod # 当前环境：[dev:本地|beta:测试|prod:生产]
  admin-user-id: 1 # 管理员用户ID
  admin-user: admin # 管理员账户登录账户
  ip: 127.0.0.1 # 当前主机 IP 地址；可使用 frp 服务器IP
  domain: http://demo.cccc6666.com # 应用路径，域名；可使用 frp 服务器域名
  markdown: http://demo.cccc6666.com/md/ # markdown 文档地址
  path-root: /var/www/demo/files # 应用文件根目录
  debug: false # 调试模式开关：true开启调试模式，false关闭调试模式
  junit: false # 单元测试开关：true开启单元测试模式，false关闭单元测试模式

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_main_db?autoReconnect=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 111111
    type: com.alibaba.druid.pool.DruidDataSource
    druid: # https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 2
      min-idle: 2
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 6000
      # 打开PSCache，并且指定每个连接上PSCache的大小，是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: false
      #max-pool-prepared-statement-per-connection-size: 10
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      #      minEvictableIdleTimeMillis: 300000
      validation-query: SELECT 1
      validation-query-timeout: 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 ,wall,log4j
      filters: stat,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "/druid/*,*.html,*.htm,*.js,*.css,*.gif,*.jpg,*.bmp,*.png,*.ico,*.svg,*.ttf,*.woff,*.woff2"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        #allow: 127.0.0.1,192.168.163.1
        # IP黑名单 (存在共同时，deny优先于allow)
        #deny: 192.168.1.73
        # 禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: druid
        # 登录密码
        login-password: druid
      filter:
        slf4j:
          enabled: true
          result-set-log-enabled: false
          # 格式化 SQL
          statement-executable-sql-log-enable: true
  #    schema: classpath:schema.sql
  #    data: classpath:database-init.sql
  data:
    mongodb:
      host: localhost
      port: 27017
      database: demo_main_db
      #uri: mongodb://name:pass@localhost/demo_main_db
