### ********************************************************************************************************************
### 用户表
### @author 谢长春 on 2020-03-08
### ********************************************************************************************************************
### 用户表: 分页查询
GET http://{{host}}:{{port}}/1/user/page/1/10
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

### 用户表: 列表查询，不分页
#GET http://{{host}}:{{port}}/1/user
#Content-Type: application/json
#Authorization: Basic {{username}} {{password}}

### 用户表: 按 id 查询单条记录
#GET http://{{host}}:{{port}}/1/user/{{id}}
#Content-Type: application/json
#Authorization: Basic {{username}} {{password}}

### 用户表: 按 id+uid 查询单条记录
GET http://{{host}}:{{port}}/1/user/{{id}}/{{uid}}
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

### 用户表: 保存
POST http://{{host}}:{{port}}/1/user
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
}

### 用户表: 修改
PUT http://{{host}}:{{port}}/1/user/{{id}}
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
}

### 用户表: 按 id 物理删除
#DELETE http://{{host}}:{{port}}/1/user/{{id}}
#Content-Type: application/json
#Authorization: Basic {{username}} {{password}}

### 用户表: 按 id + uid 物理删除
#DELETE http://{{host}}:{{port}}/1/user/{{id}}/{{uid}}
#Content-Type: application/json
#Authorization: Basic {{username}} {{password}}

### 用户表: 按 id+uid 删除单条记录
PATCH http://{{host}}:{{port}}/1/user/{{id}}/{{uid}}
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

### 用户表: 按 id 批量逻辑删除
#PATCH http://{{host}}:{{port}}/1/user
#Content-Type: application/json
#Authorization: Basic {{username}} {{password}}
#
#[1,2]

### 用户表: 按 id+uid 批量逻辑删除
PATCH http://{{host}}:{{port}}/1/user
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

[
  {
    "id": 0,
    "uid": ""
  }
]

###

