### ********************************************************************************************************************
### 用户登录记录表
### @author 谢长春 on 2020-03-08
### ********************************************************************************************************************
### 用户登录记录表: 分页查询
GET http://{{host}}:{{port}}/1/user-login/page/1/10
Content-Type: application/json


### 用户登录记录表: 列表查询，不分页
#GET http://{{host}}:{{port}}/1/user-login
#Content-Type: application/json
#

### 用户登录记录表: 按 id 查询单条记录
GET http://{{host}}:{{port}}/1/user-login/{{id}}
Content-Type: application/json


