### ********************************************************************************************************************
### 测试自定义 Convert 表
### @author 谢长春 on 2020-03-11
### ********************************************************************************************************************
### 测试自定义 Convert 表: 分页查询
GET http://{{host}}:{{port}}/1/convert/page/1/10
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

### 测试自定义 Convert 表: 列表查询，不分页
#GET http://{{host}}:{{port}}/1/convert
#Content-Type: application/json
#Authorization: Basic {{username}} {{password}}

### 测试自定义 Convert 表: 按 id 查询单条记录
#GET http://{{host}}:{{port}}/1/convert/{{id}}
#Content-Type: application/json
#Authorization: Basic {{username}} {{password}}

### 测试自定义 Convert 表: 按 id+uid 查询单条记录
GET http://{{host}}:{{port}}/1/convert/{{id}}/{{uid}}
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

### 测试自定义 Convert 表: 保存
POST http://{{host}}:{{port}}/1/convert
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
  "ids": [
    1,
    2
  ],
  "item": {
    "key": "SUCCESS",
    "value": "1",
    "comment": "成功"
  }
}
### 测试自定义 Convert 表: 保存
POST http://{{host}}:{{port}}/1/convert
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
  "items": [
    {
      "key": "SUCCESS",
      "value": "1",
      "comment": "成功"
    },
    {
      "key": "FAILURE",
      "value": "0",
      "comment": "失败"
    }
  ]
}

### 测试自定义 Convert 表: 保存
POST http://{{host}}:{{port}}/1/convert
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
  "ids": [
    100,
    101,
    102
  ]
}

### 测试自定义 Convert 表: 保存
POST http://{{host}}:{{port}}/1/convert
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
  "images": [
    "100000000000000000000000000000000000000.png",
    "200000000000000000000000000000000000000.png",
    "300000000000000000000000000000000000000.png"
  ]
}



### 测试自定义 Convert 表: 修改
PUT http://{{host}}:{{port}}/1/convert/{{id}}
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{

}

### 测试自定义 Convert 表: 按 id 物理删除
#DELETE http://{{host}}:{{port}}/1/convert/{{id}}
#Content-Type: application/json
#Authorization: Basic {{username}} {{password}}

### 测试自定义 Convert 表: 按 id + uid 物理删除
#DELETE http://{{host}}:{{port}}/1/convert/{{id}}/{{uid}}
#Content-Type: application/json
#Authorization: Basic {{username}} {{password}}

### 测试自定义 Convert 表: 按 id+uid 删除单条记录
PATCH http://{{host}}:{{port}}/1/convert/{{id}}/{{uid}}
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

### 测试自定义 Convert 表: 按 id 批量逻辑删除
#PATCH http://{{host}}:{{port}}/1/convert
#Content-Type: application/json
#Authorization: Basic {{username}} {{password}}
#
#[1,2]

### 测试自定义 Convert 表: 按 id+uid 批量逻辑删除
PATCH http://{{host}}:{{port}}/1/convert
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

[
  {
    "id": 0,
    "uid": ""
  }
]

