### 保存
POST http://{{host}}:{{port}}/demo-list/1
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
  "name": "JX",
  "content": "mMCqBHZnIEzvmYh",
  "status": "WATING",
  "amount": 1000
}

### 修改
PUT http://{{host}}:{{port}}/demo-list/1/2
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
  "uid": "8dbdec428e9547d8b11b7253774a674f",
  "name": "PeXImPsqeI",
  "content": "OyTlwNFavgqaHgc",
  "status": "RUNNING",
  "amount": 7871.1,
  "updateTime": "2019-07-21 15:21:42"
}

### 物理删除:id
DELETE http://{{host}}:{{port}}/demo-list/1/20
Authorization: Basic {{username}} {{password}}

### 物理删除:id+uid
DELETE http://{{host}}:{{port}}/demo-list/1/21/1237cf2c19de4275a62b9c1b819bca7c
Authorization: Basic {{username}} {{password}}

### 逻辑删除:id
PATCH http://{{host}}:{{port}}/demo-list/1/8
Authorization: Basic {{username}} {{password}}

### 逻辑删除:id+uid
PATCH http://{{host}}:{{port}}/demo-list/1/9/426e8907e2914451b3d6a66b8b4880c0
Authorization: Basic {{username}} {{password}}

### 批量逻辑删除:id+uid
PATCH http://{{host}}:{{port}}/demo-list/1
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

[
  {
    "id": 12,
    "uid": "e122cfb6575e442f91a4ff8310ce12d7"
  },
  {
    "id": 13,
    "uid": "0141ba6664e84a9795eb549d985b24f0"
  }
]

### 查询:id+timestamp
GET http://{{host}}:{{port}}/demo-list/1/4/1562813813000
Authorization: Basic {{username}} {{password}}

### 查询:id+uid+timestamp
GET http://{{host}}:{{port}}/demo-list/1/1/1ec365fd461b44769e61a5c4425b06d3/1562813802000
Authorization: Basic {{username}} {{password}}

### 查询:不分页
GET http://{{host}}:{{port}}/demo-list/1
Authorization: Basic {{username}} {{password}}

### 查询:不分页
GET http://{{host}}:{{port}}/demo-list/1??insertTimeRange={"begin":"2018-12-27", "end":"2018-12-27"}
Authorization: Basic {{username}} {{password}}

### 查询:分页
GET http://{{host}}:{{port}}/demo-list/1/page/1/10?amountRange={"min":0.0,"max":2000.0}
Authorization: Basic {{username}} {{password}}

### 查询:分页 + 排序
GET http://{{host}}:{{port}}/demo-list/1/page/1/10?amountRange={"min":0.0,"max":2000.0}&sorts=[{name:"updateTime", direction:"DESC"}]
Authorization: Basic {{username}} {{password}}

### 自定义方言
GET http://{{host}}:{{port}}/demo-list/1/test
Authorization: Basic {{username}} {{password}}

### 查询:不分页
GET http://{{host}}:{{port}}/demo-list/1/vo
Authorization: Basic {{username}} {{password}}

### 查询:不分页
GET http://{{host}}:{{port}}/demo-list/1/page/vo/1/10
Authorization: Basic {{username}} {{password}}

###