### 保存
POST http://localhost:8080/demo-mongo/1
Content-Type: application/json
Authorization: basic YWRtaW46YWRtaW4=

{
  "json": {
    "name": "JX",
    "phone": "18700000000",
    "status": "WATING",
    "age": 18
  }
}

###
### 修改
PUT http://localhost:8080/demo-mongo/1/728b4669e711444fbcc3401cb524b4f6
Content-Type: application/json
Authorization: basic YWRtaW46YWRtaW4=

{
  "json": {
    "name": "PeXImPsqeI",
    "content": "OyTlwNFavgqaHgc",
    "status": "RUNNING",
    "age": 150,
    "modifyTime": "2019-01-29 16:10:59.723"
  }
}

###
### 物理删除:id
DELETE http://localhost:8080/demo-mongo/1/23a05a3b9ea444c3bbb30236139ec43d
Authorization: basic YWRtaW46YWRtaW4=

###
### 逻辑删除:id
PATCH http://localhost:8080/demo-mongo/1/cd71267b47a74bcba66f540fc11727ae
Authorization: basic YWRtaW46YWRtaW4=

###
### 批量逻辑删除:id
PATCH http://localhost:8080/demo-mongo/1
Content-Type: application/json
Authorization: basic YWRtaW46YWRtaW4=

{
  "json": [
    "2bbeb79be01249de951a77fa4dcfd533",
    "8dd638a9c7a2493db0b17353a0bf0a74"
  ]
}

###
### 查询:id+timestamp
GET http://localhost:8080/demo-mongo/1/728b4669e711444fbcc3401cb524b4f6/1545100853000
Authorization: basic YWRtaW46YWRtaW4=

###
### 查询:不分页
GET http://localhost:8080/demo-mongo/1?json={"createTimeRange":{"begin":"2019-01-25", "end":"2019-01-25"}}
Authorization: basic YWRtaW46YWRtaW4=

###
### 查询:分页
GET http://localhost:8080/demo-mongo/1/page/1/10?json={"ageRange":{"min":1,"max":20}}
Authorization: basic YWRtaW46YWRtaW4=

###
