### 保存
POST http://{{host}}:{{port}}/demo-mongo/1
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
  "name": "JX",
  "phone": "18700000000",
  "status": "WATING",
  "age": 18
}

### 修改
PUT http://{{host}}:{{port}}/demo-mongo/1/e157a8b7edc5453381041946026e621a
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
  "name": "PeXImPsqeI",
  "content": "OyTlwNFavgqaHgc",
  "status": "RUNNING",
  "age": 100,
  "updateTime": "2019-07-12 18:13:54.329"
}

### 物理删除:id
DELETE http://{{host}}:{{port}}/demo-mongo/1/feb518709d1c4194b34b0e32683c04a9
Authorization: Basic {{username}} {{password}}

### 逻辑删除:id
PATCH http://{{host}}:{{port}}/demo-mongo/1/1a22b53f9777405e84725b8f0240f4ad
Authorization: Basic {{username}} {{password}}

### 批量逻辑删除:id
PATCH http://{{host}}:{{port}}/demo-mongo/1
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
  "json": [
    "2982907ed96a49ae9a30cb838ec36d5e",
    "207c1778639b41a29be3e12a811bfdfd"
  ]
}

### 查询:id+timestamp
GET http://{{host}}:{{port}}/demo-mongo/1/2923cf4d0e6c428080f9033e092e7591/1576055446904
Authorization: Basic {{username}} {{password}}

### 查询:不分页
GET http://{{host}}:{{port}}/demo-mongo/1
Authorization: Basic {{username}} {{password}}

### 查询:不分页
GET http://{{host}}:{{port}}/demo-mongo/1?json={"insertTimeRange":{"begin":"2019-01-04", "end":"2019-01-04"}}
Authorization: Basic {{username}} {{password}}

### 查询:分页
GET http://{{host}}:{{port}}/demo-mongo/1/page/1/10?json={"ageRange":{"min":1,"max":20}}
Authorization: Basic {{username}} {{password}}

###
