### 保存
POST http://localhost:8080/demo-mongo/1
Content-Type: application/json
Authorization: basic YWRtaW46YWRtaW4=

{
  "json": {
    "name": "JX",
    "phone": "18700000000",
    "status": "WATING",
    "age": 18
  }
}

### 修改
PUT http://localhost:8080/demo-mongo/1/e157a8b7edc5453381041946026e621a
Content-Type: application/json
Authorization: basic YWRtaW46YWRtaW4=

{
  "json": {
    "name": "PeXImPsqeI",
    "content": "OyTlwNFavgqaHgc",
    "status": "RUNNING",
    "age": 150,
    "modifyTime": "2019-07-12 18:13:11.838"
  }
}

### 物理删除:id
DELETE http://localhost:8080/demo-mongo/1/feb518709d1c4194b34b0e32683c04a9
Authorization: basic YWRtaW46YWRtaW4=

### 逻辑删除:id
PATCH http://localhost:8080/demo-mongo/1/d7529587c3e94f8a8385bc14c16b1020
Authorization: basic YWRtaW46YWRtaW4=

### 批量逻辑删除:id
PATCH http://localhost:8080/demo-mongo/1
Content-Type: application/json
Authorization: basic YWRtaW46YWRtaW4=

{
  "json": [
    "d7529587c3e94f8a8385bc14c16b1020",
    "83b67bebebbc4b4b8e31ee38f4f18ac0"
  ]
}

### 查询:id+timestamp
GET http://localhost:8080/demo-mongo/1/feb518709d1c4194b34b0e32683c04a9/1562926387285
Authorization: basic YWRtaW46YWRtaW4=

### 查询:不分页
GET http://localhost:8080/demo-mongo/1
Authorization: basic YWRtaW46YWRtaW4=

### 查询:不分页
GET http://localhost:8080/demo-mongo/1?json={"createTimeRange":{"begin":"2019-01-04", "end":"2019-01-04"}}
Authorization: basic YWRtaW46YWRtaW4=

### 查询:分页
GET http://localhost:8080/demo-mongo/1/page/1/10?json={"ageRange":{"min":1,"max":20}}
Authorization: basic YWRtaW46YWRtaW4=

###
