### hasNull ************************************************************************************************************
GET http://{{host}}:{{port}}/0/valid/hasNull
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/1/valid/hasNull
Authorization: Basic {{username}} {{password}}

### notNull ************************************************************************************************************
GET http://{{host}}:{{port}}/0/valid/notNull
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/1/valid/notNull
Authorization: Basic {{username}} {{password}}

### notBlank ***********************************************************************************************************
GET http://{{host}}:{{port}}/0/valid/notBlank
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/1/valid/notBlank
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/2/valid/notBlank
Authorization: Basic {{username}} {{password}}

### size ***************************************************************************************************************
GET http://{{host}}:{{port}}/0/valid/size
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/1/valid/size
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/2/valid/size
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/3/valid/size
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/4/valid/size
Authorization: Basic {{username}} {{password}}

### pattern ************************************************************************************************************
GET http://{{host}}:{{port}}/0/valid/pattern
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/1/valid/pattern
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/2/valid/pattern
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/3/valid/pattern
Authorization: Basic {{username}} {{password}}

### notEmpty ***********************************************************************************************************
GET http://{{host}}:{{port}}/0/valid/notEmpty
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/1/valid/notEmpty
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/2/valid/notEmpty
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/3/valid/notEmpty
Authorization: Basic {{username}} {{password}}

### min ****************************************************************************************************************
GET http://{{host}}:{{port}}/0/valid/min
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/1/valid/min
Authorization: Basic {{username}} {{password}}

### max ****************************************************************************************************************
GET http://{{host}}:{{port}}/0/valid/max
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/1/valid/max
Authorization: Basic {{username}} {{password}}

### decimalMin *********************************************************************************************************
GET http://{{host}}:{{port}}/0/valid/decimalMin
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/1/valid/decimalMin
Authorization: Basic {{username}} {{password}}

### decimalMax *********************************************************************************************************
###
GET http://{{host}}:{{port}}/0/valid/decimalMax
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/1/valid/decimalMax
Authorization: Basic {{username}} {{password}}

### digits *************************************************************************************************************
GET http://{{host}}:{{port}}/0/valid/digits
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/1/valid/digits
Authorization: Basic {{username}} {{password}}

### negative ***********************************************************************************************************
GET http://{{host}}:{{port}}/0/valid/negative
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/1/valid/negative
Authorization: Basic {{username}} {{password}}

### negativeOrZero *****************************************************************************************************
GET http://{{host}}:{{port}}/0/valid/negativeOrZero
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/1/valid/negativeOrZero
Authorization: Basic {{username}} {{password}}

### positive ***********************************************************************************************************
GET http://{{host}}:{{port}}/0/valid/positive
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/1/valid/positive
Authorization: Basic {{username}} {{password}}

### positiveOrZero *****************************************************************************************************
GET http://{{host}}:{{port}}/0/valid/positiveOrZero
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/1/valid/positiveOrZero
Authorization: Basic {{username}} {{password}}

### assertTrue *********************************************************************************************************
GET http://{{host}}:{{port}}/0/valid/assertTrue
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/1/valid/assertTrue
Authorization: Basic {{username}} {{password}}

### assertFalse ********************************************************************************************************
GET http://{{host}}:{{port}}/0/valid/assertFalse
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/1/valid/assertFalse
Authorization: Basic {{username}} {{password}}

### email **************************************************************************************************************
GET http://{{host}}:{{port}}/0/valid/email
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/1/valid/email
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/2/valid/email
Authorization: Basic {{username}} {{password}}

### past ***************************************************************************************************************
GET http://{{host}}:{{port}}/0/valid/past
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/1/valid/past
Authorization: Basic {{username}} {{password}}

### future *************************************************************************************************************
###
GET http://{{host}}:{{port}}/0/valid/future
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/1/valid/future
Authorization: Basic {{username}} {{password}}

### save ***************************************************************************************************************
POST http://{{host}}:{{port}}/0/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/1/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/2/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/3/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/4/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/5/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/6/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/7/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/8/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/9/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/10/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/11/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/12/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/13/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/14/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/15/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/16/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/17/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/18/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/19/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/20/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/21/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/22/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/23/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/24/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/25/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/26/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/27/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/28/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/29/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/30/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/31/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/32/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/33/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/34/valid
Authorization: Basic {{username}} {{password}}

###
POST http://{{host}}:{{port}}/35/valid
Authorization: Basic {{username}} {{password}}

### update *************************************************************************************************************
PUT http://{{host}}:{{port}}/0/valid/1
Authorization: Basic {{username}} {{password}}

###
PUT http://{{host}}:{{port}}/1/valid/1
Authorization: Basic {{username}} {{password}}

###
PUT http://{{host}}:{{port}}/2/valid/1
Authorization: Basic {{username}} {{password}}

###
PUT http://{{host}}:{{port}}/3/valid/1
Authorization: Basic {{username}} {{password}}

###
PUT http://{{host}}:{{port}}/4/valid/1
Authorization: Basic {{username}} {{password}}

###
PUT http://{{host}}:{{port}}/5/valid/1
Authorization: Basic {{username}} {{password}}

###
PUT http://{{host}}:{{port}}/6/valid/1
Authorization: Basic {{username}} {{password}}

###
PUT http://{{host}}:{{port}}/7/valid/1
Authorization: Basic {{username}} {{password}}

###
PUT http://{{host}}:{{port}}/8/valid/1
Authorization: Basic {{username}} {{password}}

###
PUT http://{{host}}:{{port}}/9/valid/1
Authorization: Basic {{username}} {{password}}

###
PUT http://{{host}}:{{port}}/10/valid/1
Authorization: Basic {{username}} {{password}}

###
PUT http://{{host}}:{{port}}/11/valid/1
Authorization: Basic {{username}} {{password}}

###
PUT http://{{host}}:{{port}}/12/valid/1
Authorization: Basic {{username}} {{password}}

###
PUT http://{{host}}:{{port}}/13/valid/1
Authorization: Basic {{username}} {{password}}

### deleteById *********************************************************************************************************
DELETE http://{{host}}:{{port}}/0/valid/1
Authorization: Basic {{username}} {{password}}

###
DELETE http://{{host}}:{{port}}/1/valid/1
Authorization: Basic {{username}} {{password}}

###
DELETE http://{{host}}:{{port}}/2/valid/1
Authorization: Basic {{username}} {{password}}

###
DELETE http://{{host}}:{{port}}/3/valid/1
Authorization: Basic {{username}} {{password}}

###
DELETE http://{{host}}:{{port}}/4/valid/1
Authorization: Basic {{username}} {{password}}

###
DELETE http://{{host}}:{{port}}/5/valid/1
Authorization: Basic {{username}} {{password}}

### deleteByUid ********************************************************************************************************
DELETE http://{{host}}:{{port}}/0/valid/1/1
Authorization: Basic {{username}} {{password}}

###
DELETE http://{{host}}:{{port}}/1/valid/1/1
Authorization: Basic {{username}} {{password}}

###
DELETE http://{{host}}:{{port}}/2/valid/1/1
Authorization: Basic {{username}} {{password}}

###
DELETE http://{{host}}:{{port}}/3/valid/1/1
Authorization: Basic {{username}} {{password}}

###
DELETE http://{{host}}:{{port}}/4/valid/1/1
Authorization: Basic {{username}} {{password}}

###
DELETE http://{{host}}:{{port}}/5/valid/1/1
Authorization: Basic {{username}} {{password}}

###
DELETE http://{{host}}:{{port}}/6/valid/1/1
Authorization: Basic {{username}} {{password}}

###
DELETE http://{{host}}:{{port}}/7/valid/1/1
Authorization: Basic {{username}} {{password}}

### markDeleteById *****************************************************************************************************
PATCH http://{{host}}:{{port}}/0/valid/1
Authorization: Basic {{username}} {{password}}

###
PATCH http://{{host}}:{{port}}/1/valid/1
Authorization: Basic {{username}} {{password}}

###
PATCH http://{{host}}:{{port}}/2/valid/1
Authorization: Basic {{username}} {{password}}

###
PATCH http://{{host}}:{{port}}/3/valid/1
Authorization: Basic {{username}} {{password}}

###
PATCH http://{{host}}:{{port}}/4/valid/1
Authorization: Basic {{username}} {{password}}

###
PATCH http://{{host}}:{{port}}/5/valid/1
Authorization: Basic {{username}} {{password}}

### markDeleteByUid ****************************************************************************************************
PATCH http://{{host}}:{{port}}/0/valid/1/1
Authorization: Basic {{username}} {{password}}

###
PATCH http://{{host}}:{{port}}/1/valid/1/1
Authorization: Basic {{username}} {{password}}

###
PATCH http://{{host}}:{{port}}/2/valid/1/1
Authorization: Basic {{username}} {{password}}

###
PATCH http://{{host}}:{{port}}/3/valid/1/1
Authorization: Basic {{username}} {{password}}

###
PATCH http://{{host}}:{{port}}/4/valid/1/1
Authorization: Basic {{username}} {{password}}

###
PATCH http://{{host}}:{{port}}/5/valid/1/1
Authorization: Basic {{username}} {{password}}

###
PATCH http://{{host}}:{{port}}/6/valid/1/1
Authorization: Basic {{username}} {{password}}

###
PATCH http://{{host}}:{{port}}/7/valid/1/1
Authorization: Basic {{username}} {{password}}

### markDelete *********************************************************************************************************
PATCH http://{{host}}:{{port}}/0/valid
Authorization: Basic {{username}} {{password}}

###
PATCH http://{{host}}:{{port}}/1/valid
Authorization: Basic {{username}} {{password}}

###
PATCH http://{{host}}:{{port}}/2/valid
Authorization: Basic {{username}} {{password}}

###
PATCH http://{{host}}:{{port}}/3/valid
Authorization: Basic {{username}} {{password}}

###
PATCH http://{{host}}:{{port}}/4/valid
Authorization: Basic {{username}} {{password}}

###
PATCH http://{{host}}:{{port}}/5/valid
Authorization: Basic {{username}} {{password}}

###
PATCH http://{{host}}:{{port}}/6/valid
Authorization: Basic {{username}} {{password}}

###
PATCH http://{{host}}:{{port}}/7/valid
Authorization: Basic {{username}} {{password}}

###
PATCH http://{{host}}:{{port}}/8/valid
Authorization: Basic {{username}} {{password}}

###
PATCH http://{{host}}:{{port}}/9/valid
Authorization: Basic {{username}} {{password}}


### findByUidTimestamp *************************************************************************************************
GET http://{{host}}:{{port}}/0/valid/1/1/1
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/1/valid/1/1/1
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/2/valid/1/1/1
Authorization: Basic {{username}} {{password}}

### search *************************************************************************************************************
GET http://{{host}}:{{port}}/0/valid
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/1/valid
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/2/valid
Authorization: Basic {{username}} {{password}}


### page ***************************************************************************************************************
###
GET http://{{host}}:{{port}}/0/valid/page/1/1
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/1/valid/page/1/1
Authorization: Basic {{username}} {{password}}

###
GET http://{{host}}:{{port}}/2/valid/page/1/1
Authorization: Basic {{username}} {{password}}

###
