spring:
  mvc:
    throw-exception-if-no-handler-found: true # 出现错误时, 直接抛出异常(便于异常统一处理，否则捕获不到404)
  resources:
    add-mappings: false # 404关闭资源映射，否则会去寻找静态资源
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  thymeleaf:
    enabled: true
    prefix: "classpath:"
    suffix: .html
    encoding: utf-8
    mode: HTML
  autoconfigure:
    exclude: # 禁用自动配置类
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure