### 单文件上传
POST http://localhost:8080/file/1/upload
Authorization: basic YWRtaW46YWRtaW4=
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="element-name.txt"
Content-Type: text/plain

Element Name
--WebAppBoundary--

### 多文件上传
POST http://localhost:8080/file/1/uploads
Authorization: basic YWRtaW46YWRtaW4=
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="element-name.txt"
Content-Type: text/plain

Element Name
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="login.http"
Content-Type: text/plain

< ./login.http

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="README.MD"
Content-Type: text/plain

< ../files/README.MD

--WebAppBoundary--

###